### PR TITLE
Fix site crashing with certain anchor links

### LINKED ISSUE #2395: URLs that contain anchors with reserved chars break the website
broken page and:

`Error: SyntaxError: Failed to execute 'querySelector' on 'Document': '#option!134' is not a valid selector.`

on 

https://dvc.org/doc/command-reference/gc#option!134

Priority depends on if we have titles (anchors with `!` and other funny symbols).

### PR DESCRIPTION
**Pull request by julieg18**
* stop code from running `querySelector` on invalid id strings

Fixes #2395

### CODE REVIEW

File: src/components/Link/index.tsx [hunk 1]
```diff
@@ -77,7 +77,7 @@ const ResultLinkComponent: React.FC<ILinkProps> = ({
 }
 
 const scrollToHash = (hash: string, scrollOptions = {}): void => {
-  if (hash) {
+  if (hash && /^[A-Za-z][-A-Za-z0-9_:.]*$/.test(hash)) {
```
Comment (julieg18) [inline src/components/Link/index.tsx:80]: Whenever an anchor link didn't match a valid HTML id, `querySelector` through an error and crashed the site. I added a regex stopping `querySelector` from running unless the anchor link is valid.

File: src/components/Link/index.tsx [hunk 2]
```diff
@@ -77,7 +77,7 @@ const ResultLinkComponent: React.FC<ILinkProps> = ({
 }
 
 const scrollToHash = (hash: string, scrollOptions = {}): void => {
-  if (hash) {
+  if (hash && /^#[A-Za-z][-A-Za-z0-9_:.]*$/.test(hash)) {
```
Comment (julieg18) [inline src/components/Link/index.tsx:80]: Whenever an anchor link didn't match a valid HTML id, querySelector through an error and crashed the site. I added a regex test stopping querySelector from running unless the anchor link is a valid id.

**Review by rogermparent — COMMENTED** [review]
I may be better to create a new function called something like `safeQuerySelector` and reuse that across both of these areas instead of copying the regex in two places.

**Comment by julieg18** [comment]
> I may be better to create a new function called something like `safeQuerySelector` and reuse that across both of these areas instead of copying the regex in two places. We could even wrap the `querySelector` call in a `try...catch` instead of regexing.

Good idea! I created a `safeQuerySelector` which uses a `try...catch` instead of using a regex.

**Review by rogermparent — APPROVED** [review]
Looks good!
