### PR TITLE
Use a unique `id` to access the app header and content body instead of a `className`

### LINKED ISSUE #681: react: unexpected URL anchor behavior when reloading a page
For example, go to https://dvc.org/doc/user-guide/managing-external-data in a new tab and then scroll down to the examples, and click the 🔗  icon that appears when hovering the cursor over the **Examples** header. This fixes the scroll position to that anchor and adds `#examples` to the URL. Now, reload the page or even select eh address bar and press Enter. The scroll is reset to the top when the page reloads, however the URL remains as https://dvc.org/doc/user-guide/managing-external-data#examples

Only if you completely close the tab and restore it (open it again) will it scroll to the correct location.

> I'm on Version 77.0.3865.90 (Official Build) (64-bit) for Mac.

### PR DESCRIPTION
**Pull request by algomaster99**
Fixes #681 
Partially addresses #714

### CODE REVIEW

**Comment by algomaster99** [comment]
@shcheklein Oh I forgot about this. :sweat_smile:  I think @iAdramelk meant to replace `className` by `id` so that it can be unique.

**Comment by shcheklein** [comment]
@algomaster99 so, if you actually introduce the change required (unique id), I think this PR will become obsolete.

**Comment by algomaster99** [comment]
@shcheklein I can push one more commit and change the title? :laughing:

**Comment by shcheklein** [comment]
@algomaster99 👍

**Comment by jorgeorpinel** [comment]
Doesn't seem to work as perfectly as the previous version. It doesn't scroll all the way to the header, the lower you go, the greater the offset. So at some point the CONTENTS table in the right side bar doesn't select the correct header either. Seems like a linear error in the offset math.

image
> https://dvc-org-pr-717.herokuapp.com/doc/tutorials/versioning#automating-capturing

**Comment by jorgeorpinel** [comment]
Also, this contains changes for #714 right? Just curious.

File: pages/doc.js [hunk 1]
```diff
@@ -20,6 +20,8 @@ import styled from 'styled-components'
 import { media } from '../src/styles'
 // sidebar data and helpers
 import sidebar, { getItemByPath } from '../src/Documentation/SidebarMenu/helper'
+// constants
+import { HEADER } from '../consts'
 
 const ROOT_ELEMENT = 'bodybag'
 const SIDEBAR_MENU = 'sidebar-menu'
```
Comment (iAdramelk) [inline pages/doc.js]: Maybe we should move this id's to the consts file too?

File: src/Tooltip/desktop-view.js [hunk 2]
```diff
@@ -18,8 +20,7 @@ class DesktopView extends Component {
   }
 
   tooltipPositionEval = () => {
-    const headerHeight = document.getElementsByClassName('header')[0]
-      .offsetHeight
+    const headerHeight = document.getElementById(HEADER).offsetHeight
     const markdownBody = document.getElementsByClassName('markdown-body')[0]
```
Comment (iAdramelk) [inline src/Tooltip/desktop-view.js]: Theoretically we can have more than 1 element with `markdown-body` class because it is the class that applies markdown css rules and there is no guaranties that  thepage body will always be the first one. Maybe we need to add unique id there and place it to consts file?

File: pages/doc.js (hunk 1 above)
Comment (algomaster99) [reply pages/doc.js]: Yeah, I have plans to. But not in this PR.

**Comment by algomaster99** [comment]
@jorgeorpinel This existed before changing it to `id` as well.
The problem is really weird though.
On checking the output of 
```
 console.log(elementBoundary.top, '= top')
```
it shows two different results when hard-reloaded and then reloading by server.
Screenshot from 2019-10-23 20-51-46

The `elementBoundary.top` signifies the position of the header w.r.t. the viewport. I am confused how it shows two different outputs.

P.S. This is only happening with markdown files with large text inside.

**Comment by shcheklein** [comment]
@algomaster99 this a known issue with pages that have images - it takes time to load them. I think it can be fixed as a separate issue (by providing a hint along with the image? I don't know yet).

@iAdramelk @algomaster99 either I don't understand what the _unique_ id mean or this is not done yet?

**Comment by algomaster99** [comment]
@shcheklein this is done. It was on hold because of https://github.com/iterative/dvc.org/pull/717#issuecomment-545170093

**Comment by algomaster99** [comment]
@shcheklein Can you open a separate issue for this delay in image loading? Also, have you thought of any solution to this?

**Comment by shcheklein** [comment]
@algomaster99 I think you should have more context to describe it - so, feel free to create a ticket :) No, I don't have any good solution in mind, except some complicated logic that will be calculating height of every # before loading. I would also take a look if it's a problem other people have tried to or solved already. I can imagine that any website that has images should have a similar issue, right?

File: src/TopMenu/index.js [hunk 3]
```diff
@@ -50,7 +52,7 @@ class TopMenu extends Component {
     return (
       <Wrapper>
         <Container
-          className="header"
```
Comment (shcheklein) [inline src/TopMenu/index.js]: are there any css rules by chance behind this class?

File: src/Tooltip/desktop-view.js (hunk 2 above)
Comment (shcheklein) [reply src/Tooltip/desktop-view.js]: @algomaster99 are you going to address this?

Comment (algomaster99) [reply src/Tooltip/desktop-view.js]: @shcheklein i think it is better to address it here https://github.com/iterative/dvc.org/issues/714

File: src/TopMenu/index.js (hunk 3 above)
Comment (algomaster99) [reply src/TopMenu/index.js]: @shcheklein I have checked it. There are none. Only place the header class is used now is in the tooltip component to style the header inside the tooltip.

File: src/Tooltip/desktop-view.js (hunk 2 above)
Comment (shcheklein) [reply src/Tooltip/desktop-view.js]: @algomaster99 It does not seem to be related to #714 . It's about changing Class to unique Id in the first place, right? and only after that about moving something to the const file.

File: src/Documentation/RightPanel/RightPanel.js [hunk 4]
```diff
@@ -6,7 +6,7 @@ import { LightButton } from '../LightButton'
 import throttle from 'lodash.throttle'
 
 const ROOT_ELEMENT = 'bodybag'
-const MARKDOWN_ROOT = '.markdown-body'
+const MARKDOWN_ROOT = '#markdown-root'
```
Comment (shcheklein) [inline src/Documentation/RightPanel/RightPanel.js]: if it's not used yet, let's remove it from this PR

Comment (algomaster99) [reply src/Documentation/RightPanel/RightPanel.js]: @shcheklein Used what? Can you please elaborate? :)

**Comment by algomaster99** [comment]
@shcheklein Since this PR doesn't only involve changing `className` to `id` for the header, I think I should also add an `id` for [`tooltip-container`](https://github.com/iterative/dvc.org/blob/593c020d3c84d4bfad077625f35c7bfff30fdb72/src/Tooltip/desktop-view.js#L30).

File: src/Documentation/RightPanel/RightPanel.js (hunk 4 above)
Comment (shcheklein) [reply src/Documentation/RightPanel/RightPanel.js]: yep, my bad, I see.

**Comment by shcheklein** [comment]
@algomaster99 let's do as a separate one.

**Comment by iAdramelk** [comment]
@algomaster99 we had similar problem on with right panel. We solved it using this code https://github.com/iterative/dvc.org/blob/master/src/Documentation/RightPanel/RightPanel.js#L11-L43

But in only solves it for images, if there is some other elements that can change container height, there is still be a bug.

**Comment by jorgeorpinel** [comment]
Can't the scrolling (re)run after `window.onload` with some vanilla JS?

**Comment by iAdramelk** [comment]
@jorgeorpinel if I remember correctly `window.onload` triggers before images are loaded.

**Comment by iAdramelk** [comment]
Easiest way to solve this problem would be by using [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver/observe), but unfortunately Safari and IE didn't support it and it's polyfills are large and slow.

**Comment by jorgeorpinel** [comment]
> The load event fires at the end of the document loading process. At this point, all of the objects in the document are in the DOM, and all the images, scripts, links and sub-frames have finished loading.

From https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload

**Comment by iAdramelk** [comment]
@jorgeorpinel Yes, you are right. I misremembered what the problem was. `window.onload` is indeed fires after initial page load. But in our case we downloading and rendering markdown files after initial page load so we can't use window.onload to find if images are loaded or not.

**Comment by jorgeorpinel** [comment]
Ah, makes sense thanks for the reminder. Oh well, scrolling seems to work great now 🙂

**Comment by jorgeorpinel** [comment]
p.s. never mind, reloading URLs with #anchors in pages with images before the anchor (e.g. https://dvc.org/doc/tutorials/versioning#preparation) still misses the offset. Should we open a separate issue for this?

**Comment by jorgeorpinel** [comment]
UPDATE: created #750 for this.

File: consts/index.js [hunk 5]
```diff
@@ -0,0 +1 @@
+export const HEADER = 'header'
```
Comment (jorgeorpinel) [inline consts/index.js]: I think this file should be located in src/ or in the root folder. Why consts/?
