### PR TITLE
test: link-check: misc fixes

### LINKED ISSUE #1148: link check: CI verision does not work properly
Example

https://dvc.org/uploads/images/2020-02-10/image.png

was detected here:

https://app.circleci.com/pipelines/github/iterative/dvc.org/2946/workflows/f15ce218-150d-4504-a5a3-647e8e721f43/jobs/2994

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] fix `git diff` (`yarn link-check-diff`) exclusion bug #1148
  + fix execution syntax `$()` bug
  + fix missing include `.` bug
  + fix missing path sep `--` bug
  + ~~use same syntax for excluding `exclude-links.txt` and `redirects-list.json`~~
    + [x] instead, whitelist-only `*.css|js|jsx|md|tsx|ts|json`
      * [x] then exclude `redirects-list.json`
- [x] support mac `sed`
- [x] spaces in file path safety
- [x] running outside repo safety
- [x] report more than just the first error per file in `git diff`s
- related #1000
- fixes #1148
- continued in #1184

### CODE REVIEW

File: scripts/link-check-git-diff.sh [hunk 1]
```diff
@@ -1,13 +1,21 @@
...
 set -euo pipefail
 
-exclude="${CHECK_LINKS_EXCLUDE_LIST:-$(dirname $0)/exclude-links.txt}"
+repo="$(dirname "$(realpath "$(dirname "$0")")")"
+pushd "$repo"
+
+exclude="${CHECK_LINKS_EXCLUDE_LIST:-$(dirname "$0")/exclude-links.txt}"
 differ="git diff $(git merge-base HEAD origin/master)"
-changed="$differ --name-only :^redirects-list.json"
+changed="$($differ --name-only -- . ':!'"$exclude" ':!redirects-list.json')"
```
Comment (casperdcl) [inline scripts/link-check-git-diff.sh:9]:
```suggestion
changed="$($differ --name-only -- '*.md' '*.js')"
```

@shcheklein this would address the missing checkbox in this PR. Seems a better idea.

Comment (shcheklein) [reply scripts/link-check-git-diff.sh:9]: may be just *.md? why are we testing sources?

Comment (shcheklein) [reply scripts/link-check-git-diff.sh:9]: it's definitely better to keep it consistent!

Comment (casperdcl) [reply scripts/link-check-git-diff.sh:9]: the link-check has always tested `js` sources (some of the entries in the exclusions list are for `js` sources). Seems logical if there are URLs appearing in `js` code.

Comment (shcheklein) [reply scripts/link-check-git-diff.sh:9]: makes sense, @casperdcl, just a bit worried about the exclusion file growing infinitely and containing old record as we go .. if we include code we now should be including `*.ts` and `*.tsx`, `js` is only a small portion of the code base now.

Comment (casperdcl) [reply scripts/link-check-git-diff.sh:9]: Ah I see those extensions have been added recently. Should add them here too, really.

Was also concerned about dead exclusions but think that can be solved separately using a script.

Comment (shcheklein) [reply scripts/link-check-git-diff.sh:9]: also, not sure if we want to include css btw? they might contain some links as well. WDYT?

Comment (casperdcl) [reply scripts/link-check-git-diff.sh:9]: Regarding that script... just automatically found these:

```
http://localhost:3000/
http://millionsongdataset.com/pages/getting-dataset/
http://ogp.me/ns
https://blog.$
https://dvc.org/img/<filename>.gif
https://dvc.org/uploads/images/2020-02-10/image.png
https://example.com/path/to/data
https://remote.dvc.org/dataset-registry/a3/04af...
https://s3-us-east-2.amazonaws.com/dvc-s3-repo/
```

Looks like we can remove them? Can also add the script to check for unused exclusions to the CI and pre-commit hook.

**Comment by casperdcl** [comment]
found more links in the additionally included files:

```
https://dvc.org/blog/$1
https://dvc.org/blog$1
https://dvc.org/doc/command-reference$1
https://s3-us-east-2.amazonaws.com/dvc-public/$1/$2
https://s3-us-east-2.amazonaws.com/dvc-s3-repo/$1
```

Presumably ok to add these to exclusions?

File: scripts/link-check-git-diff.sh (hunk 1 above)
Comment (casperdcl) [reply scripts/link-check-git-diff.sh:9]: Opened #1184

Comment (casperdcl) [reply scripts/link-check-git-diff.sh:9]: > also, not sure if we want to include css btw? they might contain some links as well. WDYT?

`finder $(git ls-files '*.css')` comes up blank :)

Comment (shcheklein) [reply scripts/link-check-git-diff.sh:9]: 👍

Comment (shcheklein) [reply scripts/link-check-git-diff.sh:9]: so, let's add them anyway - it's good that we don't have anything yet :) let's keep it clean from the very beginning

Comment (casperdcl) [reply scripts/link-check-git-diff.sh]: ok should be fine to merge now.

File: scripts/link-check-git-diff.sh [hunk 2]
```diff
@@ -1,13 +1,20 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-exclude="${CHECK_LINKS_EXCLUDE_LIST:-$(dirname $0)/exclude-links.txt}"
+repo="$(dirname "$(realpath "$(dirname "$0")")")"
+pushd "$repo"
+
 differ="git diff $(git merge-base HEAD origin/master)"
-changed="$differ --name-only :^redirects-list.json"
+changed="$($differ --name-only -- '*.css' '*.js' '*.jsx' '*.md' '*.tsx' '*.ts' '*.json')"
```
Comment (shcheklein) [inline scripts/link-check-git-diff.sh:8]: so, I thought that we want to exclude the redirects list? no?

Comment (shcheklein) [reply scripts/link-check-git-diff.sh:8]: also, WDYT about excluding tests automatically ... again, to simplify the list ... maybe can be part of the trim ticket

Comment (casperdcl) [reply scripts/link-check-git-diff.sh:8]: hah just realised I'd blindly included `*.json` which would indeed include `redirects-list.json`.

Comment (casperdcl) [reply scripts/link-check-git-diff.sh]: > also, WDYT about excluding tests automatically ... again, to simplify the list ... maybe can be part of the trim ticket

not sure exactly what you mean (e.g. CI automatically committing to exclusions?) - still probably best to discuss in #1184

Comment (casperdcl) [reply scripts/link-check-git-diff.sh]: > hah just realised I'd blindly included `*.json` which would indeed include `redirects-list.json`.

fixed now

Comment (shcheklein) [reply scripts/link-check-git-diff.sh]: I mean `*.test.js` - js tests that have a lot of links that probably won't ever make it the website
