### PR TITLE
test: link-check against merge base

### LINKED ISSUE #977: broken links detection CI looks broken
This run:

https://circleci.com/gh/iterative/dvc.org/2138

takes links from unrelated files?

### PR DESCRIPTION
**Pull request by casperdcl**
- [x] ensure links in PRs are checked against the PR diff rather than master diff
- [x] only check additions (not deletions)
- fixes #977

### CODE REVIEW

File: scripts/link-check-git-diff.sh [hunk 1]
```diff
@@ -1,3 +1,3 @@
 #!/usr/bin/env bash
 set -euxo pipefail
-$(dirname "$0")/link-check.sh <(git diff origin/master -U0)
+$(dirname "$0")/link-check.sh <(git diff $(git merge-base HEAD origin/master) -U0 | grep '^\+')
```
Comment (jorgeorpinel) [inline scripts/link-check-git-diff.sh]: Maybe you can just use `lint-staged` (used/configured in package.json) to sent the staged files into this script @casperdcl ?

Comment (casperdcl) [reply scripts/link-check-git-diff.sh]: Can't because that would affect the pre-commit hook

Comment (casperdcl) [reply scripts/link-check-git-diff.sh]: (and we can't assume devs have the prereqs to run the checks)
