### PR TITLE
Fixes #286

### LINKED ISSUE #286: confusing behavior on network fail
When trying to click on a link in menu on dvc.org while network failed it changes address and then does nothing. If you click on some top level menu item other than one you are in then menu works as expected and hide/show animation is shown for a content, but it leaves the content if the last page not new one.

### PR DESCRIPTION
**Pull request by ProjGoodF**
Fixes #286. It seems that with no connection there should be no changes.

### CODE REVIEW

**Comment by ProjGoodF** [comment]
> Either I'm missing something or behavior is the same as before. When there is no network connection it changes the URL but does not show a new page.

we disabled section selection

**Comment by shcheklein** [comment]
> we disabled section selection

When?

I still can click a section when network is not available. Check the deployment for this PR. It changes the URL and does not change the content:


Screen Shot 2019-05-07 at 11 03 01 PM

File: pages/doc.js [hunk 1]
```diff
@@ -141,6 +137,8 @@ export default class Documentation extends Component {
           }
         )
       })
+    }).catch(()=>{
```
Comment (shcheklein) [inline pages/doc.js]: will it catch any error? can it cause an infinite loop? can we actually detect a specific error to be safe here?

Comment (ProjGoodF) [reply pages/doc.js]: This will catch any http request error.
This cannot cause an endless loop.
Yes, here we can see the specific error of the http request: the code and text of the error.

Comment (shcheklein) [reply pages/doc.js]: 👍 My bad. Didn't recognize this is a promise catch.

File: pages/doc.js [hunk 2]
```diff
@@ -141,6 +137,8 @@ export default class Documentation extends Component {
...
+      window.location.reload();
```
Comment (shcheklein) [inline pages/doc.js]: let's remove `;` we don't use them in this code base
